name: Set up
description: Set up Python and Poetry
inputs:
  poetry-version:
    default: latest
  python-version:
    default: "3.11"
  working-directory:
    description: Working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: venv-${{ runner.os }}-${{ inputs.poetry-version }}

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
        cache-dependency-path: ${{ inputs.working-directory }}/poetry.lock

    - name: Install dependencies
      run: poetry install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
